Job RE-
tylt6688/Breze pull request #22
Opened 2023-03-24 07:18 UTC by Nightliuguoxing

1. 删除根据Name查询Job方法
2. 添加模糊搜素岗位接口 /searchOr
3. 添加精确搜索岗位接口 /searchAnd
4. 修复【插入/更新】 岗位名称重复 BUG
5. 删除岗位 待测试

2023-03-24 08:56 UTC, tylt6688 requested changes
全局使用DTO进行转换后操作，避免实体直接暴露

2023-03-24 08:56 UTC, tylt6688 commented on src/main/java/com/breze/controller/rbac/JobController.java
全局使用DTO进行转换后操作，避免实体直接暴露

2023-03-26 08:21 UTC, Nightliuguoxing commented
1.

2023-03-26 08:21 UTC, closed without merging

2023-03-26 08:23 UTC, Nightliuguoxing commented
1. 删除根据Name查询Job方法 
2. 添加模糊搜素岗位接口 /searchOr 
3. 添加精确搜索岗位接口 /searchAnd 
4. 修复【插入/更新】 岗位名称重复 BUG 
5. 删除岗位 有待观察
6. 修复实体暴露 添加 JobDTO